### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sgratzl**
update dev dependencies. requires that other project as well are updated to to a @types dependency change

### CODE REVIEW

**Comment by thinkh** [comment]
@sgratzl I finished the update. This branch is now working with Typescript v2.7.2. I could not update the webpack dependency though, because the most recent version v4.1 does not work with our custom webpack.config.js.

Further, I was not able to fix all Typescript compile errors properly. Please see TODO markers in the source code and fix them if possible.

**Edit:**
What are the next steps? Do we have to update the other phovea repositories, too?

**Comment by sgratzl** [comment]
does it still work with the old compiler? or do we have to update ALL other repos before we can merge that one?

**Comment by thinkh** [comment]
Good question... I tried vega_clue + this branch (which are both working with tsc v2.7.2), but using the tsc v2.2.0. Then I get the following error log:

```
webpack: Compiled successfully.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(58,25):
TS1005: ',' expected.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(80,49):
TS1005: ',' expected.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(80,51):
TS1005: '>' expected.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(80,53):
TS1128: Declaration or statement expected.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(80,57):
TS1005: ';' expected.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(81,14):
TS1005: ',' expected.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(82,19):
TS1005: ',' expected.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(83,19):
TS1005: ',' expected.
ERROR in node_modules/vega-typings/types/runtime/index.d.ts(84,13):
TS1005: ',' expected.
ERROR in phovea_core/src/ajax.ts(13,41):
TS2304: Cannot find name 'Response'.
ERROR in phovea_core/src/ajax.ts(20,32):
TS2304: Cannot find name 'Response'.
ERROR in phovea_core/src/ajax.ts(28,56):
TS2304: Cannot find name 'Response'.
ERROR in phovea_core/src/ajax.ts(67,18):
TS2304: Cannot find name 'RequestInit'.
ERROR in phovea_core/src/ajax.ts(101,36):
TS2339: Property 'fetch' does not exist on type 'Window'.
ERROR in phovea_core/src/internal/promise.ts(17,17):
TS1005: ',' expected.
ERROR in phovea_core/src/internal/promise.ts(17,31):
TS1005: ',' expected.
ERROR in phovea_core/src/internal/promise.ts(18,43):
TS2345: Argument of type 'T' is not assignable to parameter of type 'T'.
ERROR in phovea_ui/src/errors.ts(51,24):
TS2304: Cannot find name 'Response'.
ERROR in phovea_ui/src/errors.ts(51,62):
TS2304: Cannot find name 'Response'.
ERROR in phovea_ui/src/errors.ts(52,16):
TS2304: Cannot find name 'Response'.
ERROR in phovea_ui/src/errors.ts(52,44):
TS2304: Cannot find name 'Response'.
ERROR in phovea_ui/src/metaData.ts(17,21):
TS2339: Property 'fetch' does not exist on type 'Window'.
Version: typescript 2.2.0
Time: 1348ms
```

* You can ignore the vega-typings
* I assume the `Response` and `fetch` errors are cause by the old `tslib` version (which we can btw. update to [v1.9.0](https://github.com/Microsoft/tslib/releases/tag/1.9.0))

The only thing left are the errors in the `promise.ts` file that are caused by the [new TS syntax from the PromiseLike interface](https://github.com/phovea/phovea_core/pull/109/files#diff-1750303b2679c4d9121501242081e635R17). I had to update this to match the interface description. So I'm not sure if we can write a typing that works for both typescript versions.

**Comment by thinkh** [comment]
> I assume the Response and fetch errors are cause by the old tslib version (which we can btw. update to v1.9.0)

This is not part of the `tslib`, but part of the `whatwg-fetch`. However, the version of `whatwg-fetch` has not changed. So I don't know how to fix this error.

**Comment by sgratzl** [comment]
> So I don't know how to fix this error.

but the `/// <reference...` was removed

**Comment by thinkh** [comment]
I fixed everything now. The setup, as described above, is working with TS v2.2.0 and TS 2.7.2.
